# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest
- task: UiPathRunJob@2
  inputs:
    orchestratorConnection: 'AzureDevOpsSCC'
    processName: 'AzureDevOpsDemo'
    folderName: 'Non-Production/RPA CoE'
    jobType: 'NonProduction'
    user: 'desktop-uklseuq\asusgr8ii'
    machine: 'desktop-uklseuq'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
