# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  AzureDevOpsAgent01
- task: UiPathRunJob@2
  inputs:
    orchestratorConnection: 'AzureDevOpsSCC'
    processName: 'AzureDevOpsDemo'
    folderName: 'Non-Production/RPA CoE'
    jobType: 'NonProduction'
    user: 'desktop-uklseuq\asusgr8ii'
    machine: 'desktop-uklseuq'
