trigger:
 - main

pool: 
AzureDevOpsAgent01
    -task:UiPathPack@2
    inputs
      versionType:AutoVersion 
      projectJsonPath:$(Build.SourcesDirectory)\project.json
      outputPath:$(Build.ArtifactStagingDirectory)
      outputType:Process
      runWorkflowAnalysis:False
      orchestratorConnection:'AzureDevOpsSCC