trigger:
 - main

stages:
 - stage: Build
   displayName: Build Package
   jobs:
   - job: BuildPackage
   pool: AzureDevOpsAgent01
   
    - task:UiPathPack@2
    inputs:
      versionType: 'AutoVersion'
      projectJsonPath: '$(Build.SourcesDirectory)\project.json'
      outputType: 'Process'
      orchestratorConnection: 'AzureDevOpsSCC'
      outputPath: '$(Build.ArtifactStagingDirectory)'